INSERT INTO groups (name, is_open, photo, created_date, last_modified_date)
VALUES ('Galactic Explorers', true, 'https://res.cloudinary.com/dsr6kwzrr/image/upload/v1730734285/Group-1_dciejn.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Cosmic Discoveries', true, 'https://res.cloudinary.com/dsr6kwzrr/image/upload/v1730734285/Group-2_ervjar.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Interstellar Alliance', true, 'https://res.cloudinary.com/dsr6kwzrr/image/upload/v1730734285/Group-3_pi76h8.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Stellar Navigators', true, 'https://res.cloudinary.com/dsr6kwzrr/image/upload/v1730734282/Group-4_ml4fcn.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Planetary Society', true, 'https://res.cloudinary.com/dsr6kwzrr/image/upload/v1730734285/Group-5_dtee2b.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Astronomy Enthusiasts', true, 'https://res.cloudinary.com/dsr6kwzrr/image/upload/v1730734284/Group-6_ymsad9.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Space Pioneers', true, 'https://res.cloudinary.com/dsr6kwzrr/image/upload/v1730734284/Group-7_kcosnn.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Lunar Mission', true, 'https://res.cloudinary.com/dsr6kwzrr/image/upload/v1730734282/Group-8_byffg5.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Martian Colonizers', true, 'https://res.cloudinary.com/dsr6kwzrr/image/upload/v1730734285/Group-9_axn44y.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Nebula Watchers', true, 'https://res.cloudinary.com/dsr6kwzrr/image/upload/v1730734287/Group-10_zjv3vk.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Astro-philosophers', true, 'https://res.cloudinary.com/dsr6kwzrr/image/upload/v1730734285/Group-11_nzj6cy.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Celestial Observers', true, 'https://res.cloudinary.com/dsr6kwzrr/image/upload/v1730734287/Group-12_d9lx9a.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Cosmonaut Training', true, 'https://res.cloudinary.com/dsr6kwzrr/image/upload/v1730734288/Group-13_vwexhn.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Star Gazers', true, 'https://res.cloudinary.com/dsr6kwzrr/image/upload/v1730734287/Group-14_da8ors.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Black Hole Hunters', true, 'https://res.cloudinary.com/dsr6kwzrr/image/upload/v1730734287/Group-15_llyfdo.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Voyagers of the Universe', true, 'https://res.cloudinary.com/dsr6kwzrr/image/upload/v1730734287/Group-16_yeu6z4.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('The Milky Way Guild', true, 'https://res.cloudinary.com/dsr6kwzrr/image/upload/v1730734287/Group-17_k7dnl5.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Galactic Cartographers', true, 'https://res.cloudinary.com/dsr6kwzrr/image/upload/v1730734288/Group-18_mlin3a.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Space-Time Travelers', true, 'https://res.cloudinary.com/dsr6kwzrr/image/upload/v1730734293/Group-19_spfjg8.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Quantum Astronomers', true, 'https://res.cloudinary.com/dsr6kwzrr/image/upload/v1730734300/Group-20_mkvre7.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Cosmic Architects', true, 'https://res.cloudinary.com/dsr6kwzrr/image/upload/v1730734282/Group-21_lgxtuw.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Asteroid Miners', true, 'https://res.cloudinary.com/dsr6kwzrr/image/upload/v1730734283/Group-22_pervu5.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Supernova Researchers', true, 'https://res.cloudinary.com/dsr6kwzrr/image/upload/v1730734282/Group-23_gldpse.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Orbital Mechanics Club', true, 'https://res.cloudinary.com/dsr6kwzrr/image/upload/v1730734282/Group-24_q43vl5.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Satellite Engineers', true, 'https://res.cloudinary.com/dsr6kwzrr/image/upload/v1730734283/Group-25_hzfkh8.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Universe Theorists', true, 'https://res.cloudinary.com/dsr6kwzrr/image/upload/v1730734282/Group-26_pimt5x.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Exoplanet Explorers', true, 'https://res.cloudinary.com/dsr6kwzrr/image/upload/v1730734283/Group-27_modev4.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
