INSERT INTO residences (planet, country, city, created_date, last_modified_date)
VALUES ('Earth', 'USA', 'New York', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Mars', 'Aresia', 'Olympia', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Jupiter', 'Zephyria', 'Stormhold', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Venus', 'Aphrodita', 'Glowvale', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Saturn', 'Ringland', 'Orbiston', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Mercury', 'Solaris', 'Suncrest', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Uranus', 'Cryotica', 'Blueshine', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Neptune', 'Aquatopia', 'Wavegate', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Pluto', 'Frosthaven', 'Icegard', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Earth', 'Canada', 'Toronto', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Mars', 'Cydonia', 'Red Plains', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Jupiter', 'Thundara', 'Bolt City', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Venus', 'Volcaria', 'Ashenfield', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Saturn', 'Titania', 'Rimwood', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Mercury', 'Heatspire', 'Mercurial City', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Uranus', 'Glacierium', 'Frostfort', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Neptune', 'Coralys', 'Trident Bay', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Pluto', 'Snowbound', 'Frostholm', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Earth', 'UK', 'London', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Mars', 'Valles', 'Dusty Ridge', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Jupiter', 'Cyclonia', 'Tempest Town', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Venus', 'Sulphuris', 'Mist Hollow', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Saturn', 'Hyperion', 'Starlight', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Mercury', 'Flareholm', 'Scorchfield', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Uranus', 'Icelantis', 'Crystal Bay', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Neptune', 'Deepsea', 'Marina Cove', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Pluto', 'Coldreach', 'Wintergate', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Earth', 'Germany', 'Berlin', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Mars', 'Aridia', 'Sandspire', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Jupiter', 'Nimbus', 'Cloudview', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Venus', 'Verdantia', 'Green Mist', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Saturn', 'Orbiton', 'Ringtown', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Mercury', 'Brightforge', 'Firestone', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Uranus', 'Frozendell', 'Bluelight', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Neptune', 'Seafoam', 'Tideport', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Pluto', 'Icetron', 'Snowville', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Earth', 'France', 'Paris', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Mars', 'Dustaria', 'Rustvale', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Jupiter', 'Gaslands', 'Windmere', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Venus', 'Hotspring', 'Mist Peak', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Saturn', 'Ringscape', 'Orbital Isle', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Mercury', 'Infernia', 'Blazestone', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Uranus', 'Snowveil', 'Glacial Fort', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Neptune', 'Bluecrest', 'Seashore', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Pluto', 'Glacia', 'Frostbite', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Earth', 'Italy', 'Rome', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Mars', 'Redrock', 'Martian Falls', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Earth', 'Ukraine', 'Kyiv', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
