INSERT INTO friends (user_from_id, user_to_id, created_date, last_modified_date)
VALUES (1, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (3, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (5, 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (7, 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (9, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
