INSERT INTO groups (name, is_open, photo, created_date, last_modified_date)
VALUES ('Galactic Explorers', true, '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Cosmic Discoveries', true, '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Interstellar Alliance', true, '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Stellar Navigators', true, '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Planetary Society', true, '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Astronomy Enthusiasts', true, '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Space Pioneers', true, '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Lunar Mission', true, '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Martian Colonizers', true, '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Nebula Watchers', true, '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Astro-philosophers', true, '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Celestial Observers', true, '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Cosmonaut Training', true, '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Star Gazers', true, '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Black Hole Hunters', true, '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Voyagers of the Universe', true, '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('The Milky Way Guild', true, '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Galactic Cartographers', true, '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Space-Time Travelers', true, '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Quantum Astronomers', true, '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Cosmic Architects', true, '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Asteroid Miners', true, '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Supernova Researchers', true, '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Orbital Mechanics Club', true, '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Satellite Engineers', true, '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Universe Theorists', true, '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Exoplanet Explorers', true, '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
