name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  javascript-ci-checks:
    name: Automated Javascript CI checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Yarn cache
        uses: actions/cache@v3
        with:
          path: client/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('client/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Setup Node.js 20.9.0
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0

      - name: Install dependencies
        working-directory: client
        run: yarn install

      - name: Run build
        working-directory: client
        run: yarn build
