name: DOCKER_IMAGE

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Disable initramfs update
        run: sudo sed -i 's/yes/no/g' /etc/initramfs-tools/update-initramfs.conf
      -
        name: Disable man-db update
        run: sudo rm -f /var/lib/man-db/auto-update
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER_NAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_IMAGE_NAME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max